[REM] Temp remove deployment

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -56,33 +56,33 @@ jobs:
           tags: |
             ghcr.io/mart337i/deploy-it.dk:${{ github.sha }}
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs:
-      - build-and-push-image
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - build-and-push-image
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      - name: Create env file
-        run: |
-          echo "GIT_COMMIT_HASH=${{ github.sha }}" > ./envfile
-          echo "token_value=${{ secrets.token_value }}" >> ./envfile
+  #     - name: Create env file
+  #       run: |
+  #         echo "GIT_COMMIT_HASH=${{ github.sha }}" > ./envfile
+  #         echo "token_value=${{ secrets.token_value }}" >> ./envfile
 
-      - name: Verify deployment files
-        run: |
-          test -f compose.yaml || (echo "compose.yaml missing!" && exit 1)
+  #     - name: Verify deployment files
+  #       run: |
+  #         test -f compose.yaml || (echo "compose.yaml missing!" && exit 1)
 
-      - name: Docker Stack Deploy
-        uses: cssnr/stack-deploy-action@v1
-        with:
-          name: deploy-it
-          file: compose.yaml
-          host: deploy-it.dk
-          user: sysadmin
-          ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
-          env_file: ./envfile
-          registry_auth: true
-          registry_host: ghcr.io
-          registry_user: mart337i
-          registry_pass: ${{ secrets.GHCR_PASS }}
+  #     - name: Docker Stack Deploy
+  #       uses: cssnr/stack-deploy-action@v1
+  #       with:
+  #         name: deploy-it
+  #         file: compose.yaml
+  #         host: deploy-it.dk
+  #         user: sysadmin
+  #         ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
+  #         env_file: ./envfile
+  #         registry_auth: true
+  #         registry_host: ghcr.io
+  #         registry_user: mart337i
+  #         registry_pass: ${{ secrets.GHCR_PASS }}
